agria_backoffice:
  path: /bo
  methods: [GET]
  controller: App\Application\Controller\Backoffice\BackOfficeAction

agria_get_animal:
  path: /get/animal/{id}
  methods: [GET]
  controller: App\Application\Controller\Backoffice\Animal\GetAnimalAction

agria_get_animals:
  path: /get/animals
  methods: [GET]
  controller: App\Application\Controller\Backoffice\Animal\GetAnimalsAction

agria_delete_animal:
  path: /delete/animal/{id}
  methods: [GET]
  controller: App\Application\Controller\Backoffice\Animal\DeleteAnimalAction
  requirements:
    id: \d+

agria_post_animal:
  path: /add/animal
  methods: [POST]
  controller: App\Application\Controller\Backoffice\Animal\AddAnimalAction

agria_get_avatars:
  path: /get/avatars
  methods: [GET]
  controller: App\Application\Controller\Backoffice\Avatar\GetAvatarsAction